name: Test
on:
  push:
  pull_request:
jobs:
  test-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
        env:
          MEDIAWIKI_USERNAME: ${{ secrets.MEDIAWIKI_USERNAME }}
          MEDIAWIKI_PASSWORD: ${{ secrets.MEDIAWIKI_PASSWORD }}
  test-most:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm ci
      - run: npm run test:unit
      - run: npm run test:node
        env:
          MEDIAWIKI_USERNAME: ${{ secrets.MEDIAWIKI_USERNAME }}
          MEDIAWIKI_PASSWORD: ${{ secrets.MEDIAWIKI_PASSWORD }}
      # don’t run test:lint in Node 12 – no point running it twice
      # don’t run test:browser in Node 12 – needs Node fetch() (see #23)
      # don’t run test:readme in Node 12 – needs --harmony-top-level-await
  test-package-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i --package-lock-only
      - run: git diff --exit-code
