name: Test
on:
  push:
  pull_request:
jobs:
  test-full:
    runs-on: ubuntu-latest
    concurrency: testwiki
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
        env:
          MEDIAWIKI_USERNAME: ${{ secrets.MEDIAWIKI_USERNAME }}
          MEDIAWIKI_PASSWORD: ${{ secrets.MEDIAWIKI_PASSWORD }}
  test-package-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i --package-lock-only
      - run: git diff --exit-code
